In [1]:
from space_marauders.game_management.linear_algebra import DifferenceMatrix, DistanceMatrix, PositionMatrix

data_a = [
    [3, 3],
    [3, 3]
]
data_b = [
    [2, 1],
    [3, 2]
]

A = PositionMatrix(data_a)
B = PositionMatrix(data_b)
C = DifferenceMatrix(A, B)

C

pygame 2.6.1 (SDL 2.28.4, Python 3.13.2)
Hello from the pygame community. https://www.pygame.org/contribute.html


[[1 2]
 [0 1]]

In [2]:
C.transpose()

[[1 0]
 [2 1]]

In [3]:
C.column_mapping

{'column_0': 0, 'column_1': 1}

In [4]:
C.row_mapping

{'row_0': 0, 'row_1': 1}

In [5]:
D = DistanceMatrix(C)
D
# D.get_distances()

[[2.23606798 1.41421356]
 [1.41421356 1.        ]]

In [6]:
import numpy as np

D.get_distances()

array([[2.23606798],
       [1.        ]])